In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
arr1 = np.array([[1,2,3], [2,3,4]])

In [7]:
arr1.ndim

2

In [8]:
arr.ndim

1

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [13]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [14]:
np.asanyarray(np.matrix(l))

matrix([[1, 2, 3, 4, 5]])

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
a = arr
a

array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[0] = 100

In [19]:
arr


array([100,   2,   3,   4,   5])

In [27]:
a## swallow copy

array([100,   2,   3,   4,   5])

In [28]:
b = np.copy(arr) ## deep copy

In [29]:
b

array([100,   2,   3,   4,   5])

In [30]:
b[0] = 234

In [31]:
b

array([234,   2,   3,   4,   5])

In [32]:
arr

array([100,   2,   3,   4,   5])

In [33]:
a

array([100,   2,   3,   4,   5])

In [34]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [36]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [37]:
iterable = (i*i for i in range(5))

In [38]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [39]:
np.fromstring('23 45 56', sep = ' ')

array([23., 45., 56.])

In [40]:
arr.size

5

In [41]:
arr1.size

6

In [1]:
list(range(5))


[0, 1, 2, 3, 4]

In [2]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
list(range(0.4, 10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
import numpy as np
list(np.arange(0.4, 10.4, 2))

[0.4, 2.4, 4.4, 6.4, 8.4]

In [8]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [9]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [10]:
np.logspace(1,5,10, base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
np.zeros((4,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr = np.ones((3, 4))

In [18]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.empty((4, 3))

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [24]:
arr2 = np.eye(5)

In [25]:
import pandas as pd
pd.DataFrame(arr2)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [29]:
np.random.rand(2,3)# Here the mean and std can be anything, and not necessarily normallly distributed

array([[0.13771816, 0.5030732 , 0.78834153],
       [0.6814563 , 0.67213533, 0.28475134]])

In [28]:
np.random.randn(2,3)## It woll generate data evenly distributed as per standard normal distribution, where mean = 0 and std = 1

array([[-0.06412192,  1.39972465,  2.04130535],
       [-0.33686816, -0.76417585, -0.40296611]])

In [31]:
arr3 = np.random.randint(1,5, (3,4))

In [33]:
arr3.size

12

In [34]:
arr3.shape

(3, 4)

In [35]:
arr3.reshape(6,2)

array([[4, 4],
       [3, 1],
       [3, 4],
       [3, 2],
       [2, 3],
       [4, 1]])

In [36]:
arr3.reshape(4, -1)

array([[4, 4, 3],
       [1, 3, 4],
       [3, 2, 2],
       [3, 4, 1]])

In [37]:
arr3.reshape(4, -134545)

array([[4, 4, 3],
       [1, 3, 4],
       [3, 2, 2],
       [3, 4, 1]])

In [38]:
arr3.reshape(2,2,3)

array([[[4, 4, 3],
        [1, 3, 4]],

       [[3, 2, 2],
        [3, 4, 1]]])

In [39]:
a = np.random.randint(1,10,(5,6))

In [40]:
a

array([[9, 6, 5, 1, 9, 4],
       [6, 6, 8, 7, 8, 4],
       [1, 4, 2, 7, 1, 8],
       [9, 2, 4, 2, 9, 6],
       [8, 3, 5, 8, 9, 2]])

In [41]:
a > 8

array([[ True, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False, False, False,  True, False],
       [False, False, False, False,  True, False]])

In [42]:
a[a>8]

array([9, 9, 9, 9, 9])

In [43]:
a[0]

array([9, 6, 5, 1, 9, 4])

In [44]:
a[0, [0,1]]

array([9, 6])

In [47]:
a[2:4, [2,3]]

array([[2, 7],
       [4, 2]])

In [48]:
a = np.random.randint(1,3,(3,3))
b = np.random.randint(1,3,(3,3))

In [49]:
a

array([[2, 1, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [50]:
b

array([[2, 2, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [51]:
a+b

array([[4, 3, 2],
       [3, 3, 4],
       [4, 3, 2]])

In [52]:
a - b

array([[ 0, -1,  0],
       [ 1, -1,  0],
       [ 0,  1,  0]])

In [56]:
a*b## Index wise multiplication

array([[4, 2, 1],
       [2, 2, 4],
       [4, 2, 1]])

In [57]:
a@b ##Matrix multiplication

array([[7, 7, 5],
       [9, 8, 6],
       [8, 9, 7]])

In [58]:
a/b

array([[1. , 0.5, 1. ],
       [2. , 0.5, 1. ],
       [1. , 2. , 1. ]])

In [59]:
a/0

/tmp/ipykernel_85/4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [60]:
# Numpy - Broadcasting

In [74]:
arr= np.zeros((3,4))

In [75]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [77]:
a = np.array([1,2,3,4])

In [78]:
a+ arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [86]:
b = np.array([[3,4,5]])## We cant rotate a 1d array, we need a 2d array for that, so we added extra brackets

In [87]:
arr1 = arr+b.T


In [88]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [89]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [90]:
np.log(arr1)

array([[1.09861229, 1.09861229, 1.09861229, 1.09861229],
       [1.38629436, 1.38629436, 1.38629436, 1.38629436],
       [1.60943791, 1.60943791, 1.60943791, 1.60943791]])

In [91]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [92]:
np.min(arr1)

3.0

In [93]:
np.max(arr1)

5.0

In [94]:
## Numpy Manipulation

In [97]:
arr = np.random.randint(1,10, (4,4))

In [98]:
arr

array([[3, 3, 4, 9],
       [2, 4, 7, 8],
       [2, 7, 2, 7],
       [6, 7, 6, 9]])

In [99]:
arr.reshape(8,2)

array([[3, 3],
       [4, 9],
       [2, 4],
       [7, 8],
       [2, 7],
       [2, 7],
       [6, 7],
       [6, 9]])

In [100]:
arr.T

array([[3, 2, 2, 6],
       [3, 4, 7, 7],
       [4, 7, 2, 6],
       [9, 8, 7, 9]])

In [101]:
arr.flatten()

array([3, 3, 4, 9, 2, 4, 7, 8, 2, 7, 2, 7, 6, 7, 6, 9])

In [102]:
np.expand_dims(arr, axis = 1)

array([[[3, 3, 4, 9]],

       [[2, 4, 7, 8]],

       [[2, 7, 2, 7]],

       [[6, 7, 6, 9]]])

In [103]:
np.expand_dims(arr, axis = 0)

array([[[3, 3, 4, 9],
        [2, 4, 7, 8],
        [2, 7, 2, 7],
        [6, 7, 6, 9]]])

In [104]:
data = np.array([[1], [2], [3]])

In [105]:
data

array([[1],
       [2],
       [3]])

In [106]:
np.squeeze(data)

array([1, 2, 3])

In [110]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [112]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [114]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [115]:
# Numpy - Binary Opertors

In [116]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [117]:
arr1

array([[7, 2, 4, 3],
       [6, 7, 7, 7],
       [8, 5, 9, 6]])

In [118]:
arr2

array([[6, 6, 5, 8],
       [1, 2, 5, 4],
       [3, 9, 3, 1]])

In [119]:
arr1 + arr2

array([[13,  8,  9, 11],
       [ 7,  9, 12, 11],
       [11, 14, 12,  7]])

In [120]:
arr1 * arr2

array([[42, 12, 20, 24],
       [ 6, 14, 35, 28],
       [24, 45, 27,  6]])

In [121]:
arr1/arr2

array([[1.16666667, 0.33333333, 0.8       , 0.375     ],
       [6.        , 3.5       , 1.4       , 1.75      ],
       [2.66666667, 0.55555556, 3.        , 6.        ]])

In [122]:
arr1**2

array([[49,  4, 16,  9],
       [36, 49, 49, 49],
       [64, 25, 81, 36]])

In [124]:
arr1

array([[7, 2, 4, 3],
       [6, 7, 7, 7],
       [8, 5, 9, 6]])

In [125]:
~arr1

array([[ -8,  -3,  -5,  -4],
       [ -7,  -8,  -8,  -8],
       [ -9,  -6, -10,  -7]])

In [126]:
arr1 > arr2

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True]])

In [127]:
## Numpy - String Functions


In [128]:
arr = np.array(['Ranjeeta', 'Kumari'])

In [129]:
arr

array(['Ranjeeta', 'Kumari'], dtype='<U8')

In [130]:
np.char.upper(arr)


array(['RANJEETA', 'KUMARI'], dtype='<U8')

In [131]:
np.char.capitalize(arr)

array(['Ranjeeta', 'Kumari'], dtype='<U8')

In [132]:
np.char.title(arr)

array(['Ranjeeta', 'Kumari'], dtype='<U8')

In [133]:
## Numpy Mathematical Functions

In [135]:
arr1

array([[7, 2, 4, 3],
       [6, 7, 7, 7],
       [8, 5, 9, 6]])

In [136]:
np.sin(arr1)

array([[ 0.6569866 ,  0.90929743, -0.7568025 ,  0.14112001],
       [-0.2794155 ,  0.6569866 ,  0.6569866 ,  0.6569866 ],
       [ 0.98935825, -0.95892427,  0.41211849, -0.2794155 ]])

In [137]:
np.cos(arr1)

array([[ 0.75390225, -0.41614684, -0.65364362, -0.9899925 ],
       [ 0.96017029,  0.75390225,  0.75390225,  0.75390225],
       [-0.14550003,  0.28366219, -0.91113026,  0.96017029]])

In [138]:
np.tan(arr1)

array([[ 0.87144798, -2.18503986,  1.15782128, -0.14254654],
       [-0.29100619,  0.87144798,  0.87144798,  0.87144798],
       [-6.79971146, -3.38051501, -0.45231566, -0.29100619]])

In [139]:
np.log10(arr1)

array([[0.84509804, 0.30103   , 0.60205999, 0.47712125],
       [0.77815125, 0.84509804, 0.84509804, 0.84509804],
       [0.90308999, 0.69897   , 0.95424251, 0.77815125]])

In [140]:
np.exp(arr1)

array([[1.09663316e+03, 7.38905610e+00, 5.45981500e+01, 2.00855369e+01],
       [4.03428793e+02, 1.09663316e+03, 1.09663316e+03, 1.09663316e+03],
       [2.98095799e+03, 1.48413159e+02, 8.10308393e+03, 4.03428793e+02]])

In [141]:
np.power(arr1, 2)

array([[49,  4, 16,  9],
       [36, 49, 49, 49],
       [64, 25, 81, 36]])

In [142]:
np.mean(arr1)

5.916666666666667

In [143]:
np.median(arr1)

6.5

In [144]:
np.std(arr1)

1.9773017529507788

In [145]:
np.var(arr1)

3.9097222222222228

In [146]:
# Numpy - Arithemetic Operations

In [147]:
arr1

array([[7, 2, 4, 3],
       [6, 7, 7, 7],
       [8, 5, 9, 6]])

In [148]:
arr2

array([[6, 6, 5, 8],
       [1, 2, 5, 4],
       [3, 9, 3, 1]])

In [149]:
arr1 - arr2

array([[ 1, -4, -1, -5],
       [ 5,  5,  2,  3],
       [ 5, -4,  6,  5]])

In [150]:
np.subtract(arr1, arr2)

array([[ 1, -4, -1, -5],
       [ 5,  5,  2,  3],
       [ 5, -4,  6,  5]])

In [151]:
np.multiply(arr1, arr2)

array([[42, 12, 20, 24],
       [ 6, 14, 35, 28],
       [24, 45, 27,  6]])

In [152]:
np.mod(arr1, arr2)

array([[1, 2, 4, 3],
       [0, 1, 2, 3],
       [2, 5, 0, 0]])

In [153]:
np.sqrt(arr1)

array([[2.64575131, 1.41421356, 2.        , 1.73205081],
       [2.44948974, 2.64575131, 2.64575131, 2.64575131],
       [2.82842712, 2.23606798, 3.        , 2.44948974]])

In [154]:
## Numpy - Statistical functions

In [155]:
np.mean(arr1)

5.916666666666667

In [156]:
np.std(arr1)

1.9773017529507788

In [157]:
np.median(arr1)

6.5

In [160]:
# Sort, Search & Counting functions

In [163]:
arr = np.array([4, 6,32,67,22])

In [164]:
np.sort(arr)

array([ 4,  6, 22, 32, 67])

In [167]:
np.searchsorted(arr, 22)

2

In [168]:
arr1 = np.array([0, 1, 0,0,0,53,3454,67,32])

In [169]:
np.count_nonzero(arr1)

5

In [170]:
np.where(arr1 > 0)

(array([1, 5, 6, 7, 8]),)

In [174]:
np.extract(arr1 > 2, arr1)

array([  53, 3454,   67,   32])

In [175]:
## Numpy - Byte Swapping

In [176]:
arr1 

array([   0,    1,    0,    0,    0,   53, 3454,   67,   32])

In [177]:
arr1.byteswap()

array([                  0,   72057594037927936,                   0,
                         0,                   0, 3819052484010180608,
       9082916023476158464, 4827858800541171712, 2305843009213693952])

In [178]:
##Numpy - Copies and Views

In [179]:
arr1

array([   0,    1,    0,    0,    0,   53, 3454,   67,   32])

In [181]:
a = np.copy(arr1) ## deep copy, any modification in arr1 will not reflect in a

In [183]:
b = arr1.view() ## shallow copy, changes will be reflected in arr1

In [184]:
b[0] = 234

In [185]:
b

array([ 234,    1,    0,    0,    0,   53, 3454,   67,   32])

In [186]:
arr1

array([ 234,    1,    0,    0,    0,   53, 3454,   67,   32])

In [187]:
a

array([   0,    1,    0,    0,    0,   53, 3454,   67,   32])

In [188]:
## Numpy - Mtrix Library

In [189]:
import numpy.matlib as nm

In [192]:
nm.zeros(5) ## this is a matrix and not na array

matrix([[0., 0., 0., 0., 0.]])

In [191]:
nm.ones(1)

matrix([[1.]])

In [193]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
## Numpy - Linear Algebra

In [212]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [213]:
arr1

array([[3, 5, 2, 8],
       [4, 3, 4, 1],
       [2, 8, 2, 2]])

In [214]:
arr2

array([[3, 6, 3, 2],
       [8, 6, 2, 2],
       [3, 8, 3, 9]])

In [215]:
np.dot(arr1, arr2)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [216]:
arr1 @ arr2


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)